#pragma once

#include <Poseidon/Asset/Formats/Enfusion/EnfusionMount.hpp>
#include <Poseidon/Asset/Formats/Material/EmatMaterialAdapter.hpp>

#include <string>
#include <vector>

namespace Poseidon::Asset::Formats::Enfusion
{

//! RFG-063: Reforger's OWN ground cover, read from the files that define it.
//!
//! Everon's grass is not placed in the world file and it is not our grass system on
//! Enfusion terrain -- it is generated by Enfusion from a chain that every terrain
//! surface names in plain text:
//!
//!   Terrains/Common/Surfaces/Grass_03.emat
//!     PlantMat      -> Assets/Clutter/Procedural/cp_grass_03.emat   (the blade layer)
//!     ClutterConfig -> Configs/Clutter/Sets/c_set_Grass_03.conf     (the plant layer)
//!         DistributionMap -> Assets/Clutter/Masks/c_set_grass_03_CMASK.edds
//!         ClutterSet { <collection>.conf, ... }
//!             ClutterCollection { ClutterDefinition { ClutterConfig <plant>.conf, Occurrence N } }
//!                 ClutterConfig { Model <plant>.xob, MinScale, MaxScale, Density, ... }
//!
//! TWO LAYERS, and they are not the same thing. `PlantMat` is a procedural shader --
//! class `Grass`, with `Plants 8`, `BladesCount 3`, `Height`, `Edge`, and a blade
//! ATLAS -- which draws the short cover. The `ClutterSet` scatters real `.xob` MODELS
//! (nettles, yarrow) on top of it. Reading one and calling it "the grass" gets half
//! the ground wrong, so both are represented here.
//!
//! The corpus is 193 `Configs/Clutter/*.conf` files.

//! One scattered plant: a model plus how it is strewn.
struct ClutterPlant
{
    std::string configPath;   //!< the `.conf` this came from
    std::string model;        //!< `.xob`, in the archives
    float minScale = 1.0f;    //!< `MinScale`
    float maxScale = 1.0f;    //!< `MaxScale`
    float density = 0.0f;     //!< `Density`, plants per square metre
    float overlap = 0.0f;     //!< `Overlap`
    float maxDrawDistance = 0.0f; //!< `MaxDrawDistance`, a FRACTION of the clutter range
    bool useTerrainNormal = false; //!< `UseTerrainNormal` -- lie along the slope
    int occurrence = 1;       //!< the `Occurrence` weight from the collection that named it

    bool valid() const { return !model.empty(); }
};

//! The blade layer: a procedural `Grass` material, not a mesh.
struct ClutterBlades
{
    std::string materialPath; //!< the `PlantMat` `.emat`
    std::string colour;       //!< `BCRMap`
    std::string opacity;      //!< `OpacityMap`
    int plants = 0;           //!< `Plants` -- tufts per patch
    int bladesPerPlant = 0;   //!< `BladesCount`
    float height = 0.0f;      //!< `Height`, metres
    float heightRandom = 0.0f;//!< `HeightRandomOffset`
    float edge = 0.0f;        //!< `Edge` -- blade width at the base

    bool valid() const { return !colour.empty() && plants > 0; }
};

//! Everything one terrain surface says about its ground cover.
struct SurfaceClutter
{
    std::string surfacePath;         //!< the surface `.emat`
    std::string distributionMap;     //!< `DistributionMap`, a `_CMASK.edds`
    ClutterBlades blades;
    std::vector<ClutterPlant> plants;
    std::string error;               //!< empty when the chain resolved

    bool valid() const { return error.empty(); }
    bool any() const { return blades.valid() || !plants.empty(); }
};

namespace ClutterDetail
{
//! `.conf` and `.emat` share one syntax, so one parser serves both, and every path in
//! them is written `"{GUID}path"` -- which is exactly what `TextureOf` recognises and
//! strips, whether the path ends in `.edds`, `.conf` or `.xob`. `isTexture()` is "has a
//! GUID", not "names an image", so no separate accessor is needed for the references.
inline std::string PathValue(const Poseidon::Asset::Material::EmatMaterial& material, const char* key)
{
    return material.TextureOf(key);
}

inline bool ReadConf(const EnfusionMount& mount, const std::string& path,
                     Poseidon::Asset::Material::EmatMaterial& out)
{
    std::vector<uint8_t> bytes;
    if (!mount.Read(path, bytes))
        return false;
    out = Poseidon::Asset::Material::ParseEmat(
        std::string_view(reinterpret_cast<const char*>(bytes.data()), bytes.size()));
    return out.valid();
}
} // namespace ClutterDetail

//! One plant `.conf`.
inline ClutterPlant ReadClutterPlant(const EnfusionMount& mount, const std::string& confPath)
{
    ClutterPlant out;
    out.configPath = confPath;
    Poseidon::Asset::Material::EmatMaterial conf;
    if (!ClutterDetail::ReadConf(mount, confPath, conf))
        return out;
    out.model = ClutterDetail::PathValue(conf, "Model");
    out.minScale = conf.FloatOr("MinScale", 1.0f);
    out.maxScale = conf.FloatOr("MaxScale", 1.0f);
    out.density = conf.FloatOr("Density", 0.0f);
    out.overlap = conf.FloatOr("Overlap", 0.0f);
    out.maxDrawDistance = conf.FloatOr("MaxDrawDistance", 0.0f);
    out.useTerrainNormal = conf.FloatOr("UseTerrainNormal", 0.0f) > 0.5f;
    return out;
}

//! The `PlantMat` blade material.
inline ClutterBlades ReadClutterBlades(const EnfusionMount& mount, const std::string& ematPath)
{
    ClutterBlades out;
    out.materialPath = ematPath;
    Poseidon::Asset::Material::EmatMaterial mat;
    if (!ClutterDetail::ReadConf(mount, ematPath, mat))
        return out;
    out.colour = mat.TextureOf("BCRMap");
    out.opacity = mat.TextureOf("OpacityMap");
    out.plants = static_cast<int>(mat.FloatOr("Plants", 0.0f));
    out.bladesPerPlant = static_cast<int>(mat.FloatOr("BladesCount", 0.0f));
    out.height = mat.FloatOr("Height", 0.0f);
    out.heightRandom = mat.FloatOr("HeightRandomOffset", 0.0f);
    out.edge = mat.FloatOr("Edge", 0.0f);
    return out;
}

//! The whole chain for one terrain surface.
//!
//! Collections are walked for their `ClutterConfig` references the same way the prefab
//! resolver walks `.et` files: a line scan keyed on the exact property name. The
//! property parser folds sub-level tokens into the enclosing property's value list, so
//! inside `ClutterCollection { Clutter { ClutterDefinition { ... } } }` the key stops
//! being a key -- the same trap PrefabResolve documents, met again three levels down.
inline SurfaceClutter ReadSurfaceClutter(const EnfusionMount& mount, const std::string& surfaceEmat)
{
    SurfaceClutter out;
    out.surfacePath = surfaceEmat;

    Poseidon::Asset::Material::EmatMaterial surface;
    if (!ClutterDetail::ReadConf(mount, surfaceEmat, surface))
    {
        out.error = "surface material unreadable: " + surfaceEmat;
        return out;
    }

    const std::string plantMat = ClutterDetail::PathValue(surface, "PlantMat");
    if (!plantMat.empty())
        out.blades = ReadClutterBlades(mount, plantMat);

    const std::string setPath = ClutterDetail::PathValue(surface, "ClutterConfig");
    if (setPath.empty())
        return out; // a surface with no plant layer is legal -- sea bed, asphalt

    Poseidon::Asset::Material::EmatMaterial set;
    if (!ClutterDetail::ReadConf(mount, setPath, set))
    {
        out.error = "clutter set unreadable: " + setPath;
        return out;
    }
    out.distributionMap = ClutterDetail::PathValue(set, "DistributionMap");

    // Collection references, and then plant references inside them: both are bare
    // quoted strings in a nested block, so they are gathered by scanning for quoted
    // `.conf` paths rather than by key.
    const auto quotedConfs = [&mount](const std::string& path, std::vector<std::string>& outPaths)
    {
        std::vector<uint8_t> bytes;
        if (!mount.Read(path, bytes))
            return false;
        const std::string text(reinterpret_cast<const char*>(bytes.data()), bytes.size());
        size_t at = 0;
        while (true)
        {
            const size_t open = text.find('"', at);
            if (open == std::string::npos)
                break;
            const size_t close = text.find('"', open + 1);
            if (close == std::string::npos)
                break;
            std::string guid, quoted;
            Poseidon::Asset::Material::Detail::SplitGuid(text.substr(open + 1, close - open - 1), guid, quoted);
            if (quoted.size() > 5 && quoted.compare(quoted.size() - 5, 5, ".conf") == 0)
                outPaths.push_back(quoted);
            at = close + 1;
        }
        return true;
    };

    std::vector<std::string> collections;
    quotedConfs(setPath, collections);
    for (const std::string& collection : collections)
    {
        std::vector<std::string> plantConfs;
        if (!quotedConfs(collection, plantConfs))
            continue;
        for (const std::string& plantConf : plantConfs)
        {
            ClutterPlant plant = ReadClutterPlant(mount, plantConf);
            if (plant.valid())
                out.plants.push_back(std::move(plant));
        }
    }
    return out;
}

} // namespace Poseidon::Asset::Formats::Enfusion
