//! Tidewater's Caustics.js — caustics by photon splatting — ported from dgreenheck/tidewater
//! @ 4811ba48 (MIT, © DRG Software Solutions LLC). W5b.
//!
//! Two layers: the fine networks from the finest FFT cascade (512², a 256-cell grid, focal planes
//! 1.2 m and 4 m) and broad focusing from the next one (256², 128 cells, 3 m and 9 m), each
//! re-splatted every frame (`tw_caustics_splat.wgsl`) and box-filtered into a mip chain. The lookup
//! (`tw_caustics.wgsl`) is used where OP lights the submerged scene: the sea bed seen from above
//! (the water material, W3f's attenuation) and the view from below (the underwater composite,
//! with its caustic light shafts).
//!
//! What OP changes: the layer constants live in a uniform (live cascade sizes); the mips are
//! generated by render passes; the lookup has no long-wave slope / foam / sea-detail inputs; OP's
//! own terrain and object shaders are not touched (the caustic factor multiplies the direct share
//! of the light the post / water passes attenuate, as Tidewater's hookDirectModulation does).

pub const FORMAT: wgpu::TextureFormat = wgpu::TextureFormat::Rgba16Float;

/// `CauParams` in tw_caustics_splat.wgsl.
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, bytemuck::Pod, bytemuck::Zeroable)]
pub struct CauParams {
    pub sun_dir: [f32; 4],
    pub p: [f32; 4],
    pub q: [f32; 4],
}

/// One layer's constants (Caustics.js).
#[derive(Clone, Copy, Debug)]
pub struct LayerSpec {
    pub cascade: u32,
    pub res: u32,
    pub grid: u32,
    pub depths: [f32; 2],
    pub slope_level: f32,
    pub margin: f32,
}

pub const FINE: LayerSpec = LayerSpec { cascade: 3, res: 512, grid: 256, depths: [1.2, 4.0], slope_level: 1.0, margin: 0.35 };
pub const BROAD: LayerSpec = LayerSpec { cascade: 2, res: 256, grid: 128, depths: [3.0, 9.0], slope_level: 0.5, margin: 0.35 };

impl LayerSpec {
    /// vertices per side of the grid over [-margin, 1 + margin]²
    pub fn cells(&self) -> u32 {
        (self.grid as f32 * (1.0 + 2.0 * self.margin)).ceil() as u32
    }
    pub fn mips(&self) -> u32 {
        32 - self.res.leading_zeros()
    }
}

/// Indexed triangle list over a `g` x `g` quad grid ((g + 1)² vertices, row-major).
pub fn grid_indices(g: u32) -> Vec<u32> {
    let row = g + 1;
    let mut idx = Vec::with_capacity((g * g * 6) as usize);
    for y in 0..g {
        for x in 0..g {
            let a = y * row + x;
            idx.extend_from_slice(&[a, a + 1, a + row, a + row, a + 1, a + row + 1]);
        }
    }
    idx
}

struct Layer {
    spec: LayerSpec,
    view: wgpu::TextureView,
    mip_views: Vec<wgpu::TextureView>,
    mip_binds: Vec<wgpu::BindGroup>,
    index: wgpu::Buffer,
    index_count: u32,
    params: [wgpu::Buffer; 2],
    binds: Option<[wgpu::BindGroup; 2]>,
}

pub struct Caustics {
    layers: [Layer; 2],
    splat_layout: wgpu::BindGroupLayout,
    splat: wgpu::RenderPipeline,
    mip: wgpu::RenderPipeline,
    /// (fine, broad) tile sizes in metres this frame (0 before the first update)
    pub tiles: [f32; 2],
}

impl Caustics {
    pub fn new(device: &wgpu::Device) -> Self {
        use wgpu::util::DeviceExt;
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("tw_caustics"),
            source: wgpu::ShaderSource::Wgsl(include_str!("tw_caustics_splat.wgsl").into()),
        });
        let vf = wgpu::ShaderStages::VERTEX_FRAGMENT;
        let splat_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("tw_caustics_splat"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: vf,
                    ty: wgpu::BindingType::Buffer { ty: wgpu::BufferBindingType::Uniform, has_dynamic_offset: false, min_binding_size: None },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: vf,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2Array,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry { binding: 2, visibility: vf, ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering), count: None },
            ],
        });
        let mip_layout = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: Some("tw_caustics_mip"),
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 3,
                    visibility: wgpu::ShaderStages::FRAGMENT,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: true },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry { binding: 4, visibility: wgpu::ShaderStages::FRAGMENT, ty: wgpu::BindingType::Sampler(wgpu::SamplerBindingType::Filtering), count: None },
            ],
        });
        let add = wgpu::BlendComponent { src_factor: wgpu::BlendFactor::One, dst_factor: wgpu::BlendFactor::One, operation: wgpu::BlendOperation::Add };
        let pipeline = |label: &str, layout: &wgpu::BindGroupLayout, vs: &str, fs: &str, blend: Option<wgpu::BlendState>| {
            let pl = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor { label: Some(label), bind_group_layouts: &[Some(layout)], immediate_size: 0 });
            device.create_render_pipeline(&wgpu::RenderPipelineDescriptor {
                label: Some(label),
                layout: Some(&pl),
                vertex: wgpu::VertexState { module: &module, entry_point: Some(vs), compilation_options: Default::default(), buffers: &[] },
                primitive: wgpu::PrimitiveState { topology: wgpu::PrimitiveTopology::TriangleList, cull_mode: None, ..Default::default() },
                depth_stencil: None,
                multisample: wgpu::MultisampleState::default(),
                fragment: Some(wgpu::FragmentState {
                    module: &module,
                    entry_point: Some(fs),
                    compilation_options: Default::default(),
                    targets: &[Some(wgpu::ColorTargetState { format: FORMAT, blend, write_mask: wgpu::ColorWrites::ALL })],
                }),
                multiview_mask: None,
                cache: None,
            })
        };
        let splat = pipeline("tw_caustics_splat", &splat_layout, "vs_cau", "fs_cau", Some(wgpu::BlendState { color: add, alpha: add }));
        let mip = pipeline("tw_caustics_mip", &mip_layout, "vs_mip", "fs_mip", None);
        let linear = device.create_sampler(&wgpu::SamplerDescriptor {
            label: Some("tw_caustics_mip"),
            address_mode_u: wgpu::AddressMode::Repeat,
            address_mode_v: wgpu::AddressMode::Repeat,
            mag_filter: wgpu::FilterMode::Linear,
            min_filter: wgpu::FilterMode::Linear,
            ..Default::default()
        });
        let make = |spec: LayerSpec, name: &str| {
            let tex = device.create_texture(&wgpu::TextureDescriptor {
                label: Some(name),
                size: wgpu::Extent3d { width: spec.res, height: spec.res, depth_or_array_layers: 1 },
                mip_level_count: spec.mips(),
                sample_count: 1,
                dimension: wgpu::TextureDimension::D2,
                format: FORMAT,
                usage: wgpu::TextureUsages::RENDER_ATTACHMENT | wgpu::TextureUsages::TEXTURE_BINDING,
                view_formats: &[],
            });
            let view = tex.create_view(&wgpu::TextureViewDescriptor::default());
            let mip_views: Vec<wgpu::TextureView> = (0..spec.mips())
                .map(|m| tex.create_view(&wgpu::TextureViewDescriptor { base_mip_level: m, mip_level_count: Some(1), ..Default::default() }))
                .collect();
            let mip_binds = (1..spec.mips() as usize)
                .map(|m| {
                    device.create_bind_group(&wgpu::BindGroupDescriptor {
                        label: Some(name),
                        layout: &mip_layout,
                        entries: &[
                            wgpu::BindGroupEntry { binding: 3, resource: wgpu::BindingResource::TextureView(&mip_views[m - 1]) },
                            wgpu::BindGroupEntry { binding: 4, resource: wgpu::BindingResource::Sampler(&linear) },
                        ],
                    })
                })
                .collect();
            let idx = grid_indices(spec.cells());
            let index = device.create_buffer_init(&wgpu::util::BufferInitDescriptor { label: Some(name), contents: bytemuck::cast_slice(&idx), usage: wgpu::BufferUsages::INDEX });
            let ubo = || {
                device.create_buffer(&wgpu::BufferDescriptor {
                    label: Some(name),
                    size: std::mem::size_of::<CauParams>() as u64,
                    usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
                    mapped_at_creation: false,
                })
            };
            Layer { spec, view, mip_views, mip_binds, index, index_count: idx.len() as u32, params: [ubo(), ubo()], binds: None }
        };
        Self { layers: [make(FINE, "tw_caustics_fine"), make(BROAD, "tw_caustics_broad")], splat_layout, splat, mip, tiles: [0.0; 2] }
    }

    pub fn fine_view(&self) -> &wgpu::TextureView {
        &self.layers[0].view
    }

    pub fn broad_view(&self) -> &wgpu::TextureView {
        &self.layers[1].view
    }

    /// (Re)bind the FFT derivatives (after the FFT's textures exist / change).
    pub fn rebuild_bind(&mut self, device: &wgpu::Device, derivatives: &wgpu::TextureView, smp_linear_repeat: &wgpu::Sampler) {
        let layout = &self.splat_layout;
        for l in &mut self.layers {
            let b = |k: usize| {
                device.create_bind_group(&wgpu::BindGroupDescriptor {
                    label: Some("tw_caustics_splat"),
                    layout,
                    entries: &[
                        wgpu::BindGroupEntry { binding: 0, resource: l.params[k].as_entire_binding() },
                        wgpu::BindGroupEntry { binding: 1, resource: wgpu::BindingResource::TextureView(derivatives) },
                        wgpu::BindGroupEntry { binding: 2, resource: wgpu::BindingResource::Sampler(smp_linear_repeat) },
                    ],
                })
            };
            let binds = [b(0), b(1)];
            l.binds = Some(binds);
        }
    }

    /// This frame's constants: `sun`: toward the sun (world); `sizes`: the FFT cascade sizes.
    pub fn set_frame(&mut self, queue: &wgpu::Queue, sun: [f32; 3], sizes: [f32; 4]) {
        for (li, l) in self.layers.iter().enumerate() {
            let tile = sizes[l.spec.cascade as usize];
            self.tiles[li] = tile;
            for k in 0..2 {
                let p = CauParams {
                    sun_dir: [sun[0], sun[1], sun[2], 0.0],
                    // (w: the cells across [-margin, 1 + margin], Tidewater's `this.grid`)
                    p: [tile, l.spec.depths[k], l.spec.margin, l.spec.cells() as f32],
                    q: [l.spec.cascade as f32, l.spec.slope_level, k as f32, 0.0],
                };
                queue.write_buffer(&l.params[k], 0, bytemuck::bytes_of(&p));
            }
        }
    }

    /// Splat both layers and build their mip chains (Caustics.update).
    pub fn dispatch(&self, encoder: &mut wgpu::CommandEncoder) {
        for l in &self.layers {
            let Some(binds) = &l.binds else { continue };
            {
                let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                    label: Some("tw_caustics_splat"),
                    color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                        view: &l.mip_views[0],
                        depth_slice: None,
                        resolve_target: None,
                        ops: wgpu::Operations { load: wgpu::LoadOp::Clear(wgpu::Color::TRANSPARENT), store: wgpu::StoreOp::Store },
                    })],
                    depth_stencil_attachment: None,
                    timestamp_writes: None,
                    occlusion_query_set: None,
                    multiview_mask: None,
                });
                pass.set_pipeline(&self.splat);
                pass.set_index_buffer(l.index.slice(..), wgpu::IndexFormat::Uint32);
                for b in binds {
                    pass.set_bind_group(0, b, &[]);
                    pass.draw_indexed(0..l.index_count, 0, 0..1);
                }
            }
            for (m, bind) in l.mip_binds.iter().enumerate() {
                let mut pass = encoder.begin_render_pass(&wgpu::RenderPassDescriptor {
                    label: Some("tw_caustics_mip"),
                    color_attachments: &[Some(wgpu::RenderPassColorAttachment {
                        view: &l.mip_views[m + 1],
                        depth_slice: None,
                        resolve_target: None,
                        ops: wgpu::Operations { load: wgpu::LoadOp::Clear(wgpu::Color::TRANSPARENT), store: wgpu::StoreOp::Store },
                    })],
                    depth_stencil_attachment: None,
                    timestamp_writes: None,
                    occlusion_query_set: None,
                    multiview_mask: None,
                });
                pass.set_pipeline(&self.mip);
                pass.set_bind_group(0, bind, &[]);
                pass.draw(0..3, 0..1);
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn layers_match_tidewater() {
        assert_eq!(FINE.cells(), 436); // ceil(256 x 1.7)
        assert_eq!(BROAD.cells(), 218);
        assert_eq!(FINE.mips(), 10);
        assert_eq!(BROAD.mips(), 9);
        let idx = grid_indices(2);
        assert_eq!(idx.len(), 24);
        assert_eq!(&idx[0..6], &[0, 1, 3, 3, 1, 4]);
        assert_eq!(std::mem::size_of::<CauParams>(), 48);
    }

    #[test]
    fn shaders_validate() {
        for (name, src) in [("tw_caustics_splat.wgsl", include_str!("tw_caustics_splat.wgsl"))] {
            let module = naga::front::wgsl::parse_str(src).unwrap_or_else(|e| panic!("{name}: {e}"));
            naga::valid::Validator::new(naga::valid::ValidationFlags::all(), naga::valid::Capabilities::all())
                .validate(&module)
                .unwrap_or_else(|e| panic!("{name}: {e:?}"));
        }
    }
}
